exports.FETCH_MOVIE_LIST = 'FETCH_MOVIE_LIST';
exports.FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS';
exports.FETCH_MOVIE_DETAIL = 'FETCH_MOVIE_DETAIL';
exports.FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';
